# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c274014d1265152bf8b82944b3731ccb319d0a0a410d2d109eebf23819eb4803c9fef56bdae0c661acf35c91ea1650cf6330e9948813894d3bda596f8cba2bf5

test:
  secret_key_base: 3f3805f1716d542e72b13b8d146622fa019544c5ae87a2e2e3dd502d081178d81f28f8a73c44950ef7193951842cd5b18a00e0f28c910fbf4ca0494eff56d139

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
